version: '3'

services:
  ci-build:
    environment:
      - DOCKER_HOST=tcp://192.168.109.152:2375
    image: microsoft/aspnetcore-build:1.0-2.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Test.sln && dotnet publish ./Test.sln -c Release -o ./obj/Docker/publish"
